import { EnvUtils } from "@repo/utils";
import OpenAI from "openai";
import { OllamaAIEnvVars, OllamaModelsNativeTools } from "..";
import { ChatCompletionMessageParam } from "openai/resources";
// https://docs.ollama.com/capabilities/tool-calling#javascript


export type CreateResponseInput = Parameters<OpenAI['responses']['create']>[0];

interface StartChatInput{
  inputList: Array<ChatCompletionMessageParam>;//CreateResponseInput["input"];
  toolsDefinitions: CreateResponseInput["tools"];
  tools: Record<string, (...args: any[]) => any>;
  instructions?: CreateResponseInput["instructions"];
  tool_choice?: CreateResponseInput["tool_choice"];
  truncation?: CreateResponseInput["truncation"];
}

export class NativeTools extends OpenAI {
    public model: OllamaModelsNativeTools;  
  
    constructor(
        model:OllamaModelsNativeTools,
        protected baseUrl: string = EnvUtils.getEnvVariable<OllamaAIEnvVars>("OLLAMA_API_BASE_URL"),
        public apiKey: string = EnvUtils.getEnvVariable<OllamaAIEnvVars>("OLLAMA_API_KEY")
      ) {
        super({
          baseURL: baseUrl,
          apiKey: apiKey,
        });
        this.model = model;
  }

  async startChat({inputList, toolsDefinitions, tools, instructions, tool_choice, truncation}: StartChatInput) {
    const res = await this.responses.create({
      model: this.model,
      input:inputList as CreateResponseInput["input"],
      tools: toolsDefinitions,
      instructions,
      tool_choice: tool_choice || "required",
      truncation: truncation || "auto"
    })

    for (const item of res.output) {
      switch (item.type) {
        case "function_call":{
          const functionName = item.name;
          const functionArgs = JSON.parse(item.arguments);
          const func = tools[functionName as keyof typeof tools];
          if(!func){
            console.error(`No function found for name: ${functionName}`);
            throw new Error(`No function found for name: ${functionName}`);
          }
          
          const res = await func(functionArgs);
          console.log(`>>> Function ${functionName} executed. Result:`, res);
          (inputList as any).push({
            type: "function_call_output",
            call_id: item.call_id,
            output: JSON.stringify(res)
          });

          const response = await this.responses.create({
            model: "gpt-5",
            instructions: "Respond only with a horoscope generated by a tool.",
            tools: toolsDefinitions,
            input: inputList as CreateResponseInput["input"],
          });
          return response.output;
        }
        default: {
          console.log(`📢 default output... item.type = `, item.type, item);
          return res.output;
        }
      }
    }
  }
}

// // 1. Define a list of callable tools for the model
// const tools = [
//   {
//     type: "function",
//     name: "get_horoscope",
//     description: "Get today's horoscope for an astrological sign.",
//     parameters: {
//       type: "object",
//       properties: {
//         sign: {
//           type: "string",
//           description: "An astrological sign like Taurus or Aquarius",
//         },
//       },
//       required: ["sign"],
//     },
//   },
// ];

// function getHoroscope(sign) {
//   return sign + " Next Tuesday you will befriend a baby otter.";
// }

// // Create a running input list we will add to over time
// let input = [
//   { role: "user", content: "What is my horoscope? I am an Aquarius." },
// ];

// // 2. Prompt the model with tools defined
// let response = await openai.responses.create({
//   model: "gpt-5",
//   tools,
//   input,
// });

// response.output.forEach((item) => {
//   if (item.type == "function_call") {
//     if (item.name == "get_horoscope"):
//       // 3. Execute the function logic for get_horoscope
//       const horoscope = get_horoscope(JSON.parse(item.arguments))
      
//       // 4. Provide function call results to the model
//       input_list.push({
//           type: "function_call_output",
//           call_id: item.call_id,
//           output: json.dumps({
//             horoscope
//           })
//       })
//   }
// });

// console.log("Final input:");
// console.log(JSON.stringify(input, null, 2));

// response = await openai.responses.create({
//   model: "gpt-5",
//   instructions: "Respond only with a horoscope generated by a tool.",
//   tools,
//   input,
// });

// // 5. The model should be able to give a response!
// console.log("Final output:");
// console.log(JSON.stringify(response.output, null, 2));